# -  /SuhailTechInfo/

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/Maduradilshan/DILSHAN-MD /root/Maduradilshan
WORKDIR /root/Maduradilshan/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /SuhailTechInfo/
